### DISCUSSION TITLE
ESPHome example with Home Assistant (Rabbit R1 Style)

### DISCUSSION THREAD

**Discussion by TitoTB** [witnessmenow/ESP32-Cheap-Yellow-Display#248] [Show and tell]
Hi everybody! I just made my project with CYD in order to control Home Assistant through ESPHome. It shows you date and time, sensors, and it allows you to control your devices. Design is inspired by Rabbit R1 (i call it Habbit) 😅

![PXL_20240726_090524916](https://github.com/user-attachments/assets/8395693e-d64e-4522-b591-7ec112faaaef)
![PXL_20240726_090712615](https://github.com/user-attachments/assets/500c259a-5ce5-4ee9-9865-91b2106bcda9)
![PXL_20240726_090723822](https://github.com/user-attachments/assets/f1b7f2a2-a233-4559-87e3-db499708d089)

See how it works!

https://youtube.com/shorts/nNfdQfwtCJw?feature=share

I would love to share the code with the community and include it in the repo if you like it! (just don't know how to do it 😅)

Anyway, you can find it in my blog to copy and paste https://aguacatec.es/integrar-la-cheap-yellow-display-en-ha/

**Comment by DreadorUK** [comment]
Hi 

Trying to reverse engineer for a more simple requirement of showing the temperature of my hot water thermostat 

Key etc above and then have this

```
# Setup WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Define SPI for the display
spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12

# Define the display with invert_colors option
display:
  - platform: ili9xxx
    id: esp_display
    model: ili9342
    spi_id: tft
    cs_pin: GPIO15
    dc_pin: GPIO2
    rotation: 90
    invert_colors: false  # Set this to false or true depending on your display
    lambda: |-
      it.fill(Color::BLACK);  // Background color
      it.print(60, 60, id(fecha), "Temperature:");
      it.printf(60, 100, id(hora), "%.1f °C", id(temperature).state);



# Create the font to use
font:
  - file: "gfonts://Space Grotesk"
    id: fecha
    size: 15
  - file: "gfonts://Space Grotesk"
    id: hora
    size: 30

# Fetch data from Home Assistant
sensor:
  - platform: homeassistant
    id: temperature
    entity_id: sensor.imersion_current_temperature  # Replace with the entity you want
    internal: true
```

Seems to compile fine and installs but then screen is still blank any idea what I did wrong in my reverse engineering as such?

Worked out why - I have KOC knock Off CYD my board is ESP32-024
