### DISCUSSION TITLE
Imposter CYD's working YAML

### DISCUSSION THREAD

**Discussion by DreadorUK** [witnessmenow/ESP32-Cheap-Yellow-Display#314] [General]
Hope this helps others - I purchased two variants and now have managed to tweak two working YAML as starting point for them

Usual API key and Wifi settings etc should be before below...

ESP32-024

```
i2c:
  - sda: 21
    scl: 22
    scan: true
spi:  
  - id: tft        
    clk_pin: 14    
    mosi_pin: 13   
    miso_pin: 12  
output:
  - id: backlight_ctrl
    platform: gpio
    pin: 27  
    inverted: false
light:
  - platform: binary
    name: "Display Backlight"
    output: backlight_ctrl
    restore_mode: ALWAYS_ON
display:
  - id: main_display
    platform: ili9xxx
    model:  TFT 2.4R    
    spi_id: tft
    cs_pin:
      number: 15
      ignore_strapping_warning: true
    dc_pin:
      number:  2
      ignore_strapping_warning: true
    invert_colors: true    
    color_palette: 8BIT   
    update_interval: never
    auto_clear_enabled: false
    transform:            
      swap_xy: true
      mirror_x: false
    dimensions:           
      height: 320
      width: 240
touchscreen:
  - platform: xpt2046
    cs_pin: 33         
    calibration:
      x_min: 280       
      x_max: 3860      
      y_min: 340       
      y_max: 3860      
    transform:
      swap_xy: true    
      mirror_x: false
      mirror_y: true    
lvgl:
  buffer_size: 25%
```

ESP-242S028 (bigger 3.5" screen)

```
i2c:
  - sda: 27
    scl: 22
    scan: true
spi:
  - id: tft
    clk_pin: 14
    mosi_pin: 13
    miso_pin:
      number: 12
      ignore_strapping_warning: true
  - id: touch
    clk_pin: 25
    mosi_pin: 32
    miso_pin: 39
output:
  - id: backlight_pwm
    platform: ledc
    pin: 21
  - id: output_red
    platform: ledc
    pin: 4
    inverted: true
  - id: output_green
    platform: ledc
    pin: 16
    inverted: true
  - id: output_blue
    platform: ledc
    pin: 17
    inverted: true
light:
  - id: backlight
    platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    restore_mode: ALWAYS_ON
  - id: led
    platform: rgb
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF
display:
  - id: main_display
    platform: ili9xxx
    model:  TFT 2.4R    
    spi_id: tft
    cs_pin:
      number: 15
      ignore_strapping_warning: true
    dc_pin:
      number:  2
      ignore_strapping_warning: true
    invert_colors: true   
    color_palette: 8BIT   
    update_interval: never
    auto_clear_enabled: false
    transform:            
      swap_xy: true
      mirror_x: false
    dimensions:          
      height: 320
      width: 240
touchscreen:
  - id: main_touchscreen
    platform: xpt2046
    spi_id: touch
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860
    transform:        
      mirror_x: false 
      mirror_y: true 
      swap_xy: false  
lvgl:
  buffer_size: 25%
```
