### ISSUE TITLE
ESPHome example with emoji fonts

### ISSUE THREAD

**Issue by arthurlutz** [witnessmenow/ESP32-Cheap-Yellow-Display#125]
I've added emoji fonts to have some nice looking icons in my project derived from the examples here. Would it be useful for other to have an example with emojis embedded ? 

```yaml
  - file: 'fonts/NotoEmoji-VariableFont_wght.ttf'
    id: noto14
    size: 14
    glyphs: "🌧🌦⛅🔌🎶☀ "

```
and in display : 

```
        it.print(0, 220, id(noto14), TextAlign::TOP_LEFT, "🌧");
```
