### ISSUE TITLE
Example "Examples/ESPHome/6-VariousFeatures" does not compile with recent esphomes.

### ISSUE THREAD

**Issue by AnHardt** [witnessmenow/ESP32-Cheap-Yellow-Display#205]
Example "Examples/ESPHome/6-VariousFeatures" does not compile with recent esphomes.

New "calibration" format for the touchscreen is easily resolve by:
```
  calibration:
    x_min: 280
    x_max: 3800
    y_min: 400
    y_max: 3900
  transform:
    mirror_x: false
    mirror_y: false
    swap_xy: true
  calibration:
    x_min: 280
    x_max: 3800
    y_min: 400
    y_max: 3900
  transform:
    mirror_x: false
    mirror_y: false
    swap_xy: true
``` 
or simmilars.

But i can't get around the common pin usage of GPIO25 used in the 'spi_touch' as well as the 'i2s_audio' component.

Is there any weay to get around that?
